external_components:
  - source:
      type: local
      path: components

esphome:
  name: alternator-regulator
  friendly_name: "Alternator regulator based on M5Stack and ESPHome"
  project:
    name: "hsteinhaus.alternator_regulator"
    version: "0.1"
  platformio_options:
    upload_speed: 2000000
    board_build.f_cpu: 240000000L
    board_build.f_flash: 80000000L
    board_build.arduino.memory_type: qio_qspi
  on_boot:
    then:
      - lambda:
          App.set_loop_interval(0);

esp32:
  board: m5stack-core-esp32
  framework:
    type: arduino
  # framework:
  #   type: esp-idf
  #   version: latest
  #   sdkconfig_options:
  #     # ESP32
  #     CONFIG_ESP32_DEFAULT_CPU_FREQ_240: "y"
  #     CONFIG_ESP32_DEFAULT_CPU_FREQ_MHZ: "240"

debug:
  update_interval: 5s

web_server:
  port: 80
  #ota: true
  local: true
  version: 3
  sorting_groups:
    - id: pps_group
      name: "Power Supply Module"
      sorting_weight: 90

# Enable logging
logger:
  level: INFO

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_password

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  reboot_timeout: 0s
  domain: .devices.home
  networks:
    - ssid: !secret wifi_ssid_02
      password: !secret wifi_password_02

##############################################################################
i2c:
  id: bus_a
  frequency: 2MHz
  scan: False
  sda: GPIO21
  scl: GPIO22

m5stack_pps:
  i2c_id: bus_a
  id: pps1

sensor:
  - platform: debug
    free:
      name: "Heap Free"
    loop_time:
      name: "Loop Time"

  - platform: m5stack_pps
    m5stack_pps: pps1
    mode:
      id: current_mode
      name: "Output mode"
      web_server:
        sorting_group_id: pps_group
    voltage:
      id: actual_voltage
      name: "Actual voltage"
      web_server:
        sorting_group_id: pps_group
    current:
      id: actual_current
      name: "Actual current"
      web_server:
        sorting_group_id: pps_group
    power:
      id: actual_power
      name: "Actual power"
      web_server:
        sorting_group_id: pps_group


number:
  - platform: m5stack_pps
    m5stack_pps: pps1
    channel: voltage
    name: "Set voltage"
    id: set_voltage
    web_server:
      sorting_group_id: pps_group

  - platform: m5stack_pps
    m5stack_pps: pps1
    channel: current
    name: "Set current"
    id: set_current
    web_server:
      sorting_group_id: pps_group


switch:
  - platform: m5stack_pps
    name: "Output enable"
    m5stack_pps: pps1
    web_server:
      sorting_group_id: pps_group
